name: CI
on: [ push, pull_request ]

jobs:
  lint-and-test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: moneymeets/action-setup-python-poetry@master

      - uses: moneymeets/moneymeets-composite-actions/lint-python@master

      - run: poetry run pytest --cov --cov-fail-under=90
